version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
      POSTGRES_DB: rails
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # persist data
  api:
    build:
      dockerfile: Dockerfile.api
    environment:
      DATABASE_URL: postgres://rails:rails@postgres:5432/rails
    ports:
      - 8080:80