version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # persist data
  lumen:
    image: wattsworth/lumen:latest # use Docker Hub image
    #build: # use the local Dockerfile
    #  dockerfile: Dockerfile
    #  context: container
    environment:
      SEND_EMAILS: ${SEND_EMAILS}
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_AUTHENTICATION: ${SMTP_AUTHENTICATION}
      SMTP_ENABLE_STARTTLS_AUTO: ${SMTP_ENABLE_STARTTLS_AUTO}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}

      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      BANNER: ${BANNER}
      HOSTNAME: ${HOSTNAME}
      SUBDOMAIN_APPS: ${SUBDOMAIN_APPS}
      RAILS_ENV: ${RAILS_ENV}

    restart: always
    ports:
      - 8080:80