version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
      POSTGRES_DB: rails
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # persist data
  api:
    build:
      dockerfile: Dockerfile.api
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    environment:
      DATABASE_URL: postgres://rails:rails@postgres:5432/rails
    ports:
      - 3000:3000
  frontend:
    build:
      dockerfile: Dockerfile.frontend
    environment:
      API_URL: http://api:3000
    ports:
      - 8080:80
  nginx:
    build:
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      API_URL: http://api:3000
      FRONTEND_URL: http://frontend:80
    ports:
      - 8080:80
      - 4430:443