FROM node:18 as node
WORKDIR /app
RUN echo "hi"
RUN git clone https://github.com/wattsworth/lumen-client.git /app
RUN npm install
RUN npm run build --production

FROM nginx:alpine
COPY --from=node /app/dist/lumen /usr/share/nginx/html
