#From https://www.infracloud.io/blogs/multi-arch-containers-ci-cd-integration/
name: docker-multi-arch-push
on:
  push:
    branches:
      - 'main'
jobs:
  docker-build-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Login to docker.io container registry
        uses: docker/login-action@v2
        with:
          username: wattsworth
          password: dckr_pat_NswiNbK4Krq-tzM5SDyBbq-TpYw


      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: container
          file: ./container/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: wattsworth/lumen:latest

